"""empty message

Revision ID: 51d2ad0d9c21
Revises: 
Create Date: 2022-01-11 13:31:40.400166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d2ad0d9c21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bybit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bybitid', sa.String(length=32), nullable=True),
    sa.Column('second_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegramid', sa.Integer(), nullable=False),
    sa.Column('verified', sa.String(length=255), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('second_name', sa.String(length=255), nullable=True),
    sa.Column('inviter_id', sa.String(length=255), nullable=True),
    sa.Column('api_secret', sa.String(length=255), nullable=True),
    sa.Column('auth_token', sa.String(length=255), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegramid')
    )
    op.create_table('trade_defaults',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegramid', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.String(length=50), nullable=True),
    sa.Column('takeprofit', sa.String(length=50), nullable=True),
    sa.Column('stoploss', sa.String(length=50), nullable=True),
    sa.Column('trailingstop', sa.String(length=50), nullable=True),
    sa.Column('newtrailingactive', sa.String(length=50), nullable=True),
    sa.Column('leverage', sa.String(length=50), nullable=True),
    sa.Column('mtype', sa.String(length=50), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_defaults')
    op.drop_table('telegram')
    op.drop_table('bybit')
    op.drop_table('admins')
    # ### end Alembic commands ###
